apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: vcs-trigger
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: miguel-hidalgo-pipeline-run-
      spec:
        pipelineRef:
          name: e2e-pipeline
        serviceAccountName: build-bot
        params:
          - name: app-name
            value: e2e-assignment-app
          - name: source-repo
            value: https://github.com/hidsan/e2e-nextjs-app.git
          - name: image-repo
            value: quay.io/miguel_hidalgo_ibm/e2e-assignment-app
        workspaces:
          - name: pipeline-shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi